### ISSUE TITLE
Saving data to a file for later analysis

### ISSUE THREAD

**Issue by foxittt** [semuconsulting/PyGPSClient#19]
Hello

Is it possible to implement the saving of data streams(UBX, NMEA, RTCM) in the appropriate files for further analysis.

**Comment by semuadmin** [comment]
Hi @foxittt 

PyGPSClient already supports datalogging:

<img width="228" alt="PyGPSClient datalogging" src="https://user-images.githubusercontent.com/28569967/165052800-973f5172-51a5-4f2b-8d3c-a5550ad13708.png">

Simply click the 'Enable Datalog' checkbox _prior to_ connecting to your receiver and select the required format (binary, parsed, hex string or tabular hex). You'll be prompted to select the folder into which the timestamped datalog files are saved. If you wish to replay the datalog within PyGPSClient, choose the binary format.

If you only want to log a particular protocol (e.g. UBX or RTCM), simply de-select the protocols you don't want to see using the 'Protocols Displayed' checkboxes:

<img width="302" alt="PyGPSClient Protocols Displayed" src="https://user-images.githubusercontent.com/28569967/165053508-27ed20b6-d53a-45ac-8dd6-3a37ded02c99.png">

Hope this helps (this information is all in the README, by the way).

**Comment by foxittt** [comment]
Thanks for answer.
Trying to log rtcm stream from ntripserver.
But there is the mistake.

**Comment by semuadmin** [comment]
For what purpose, out of interest? What 'further analysis' would you be looking to undertake?

**Comment by foxittt** [comment]
For example, how different parameters change during the day: the number of visible satellites, how a certain location changes compared to the true and compared to the average.

**Comment by semuadmin** [comment]
OK fair enough. It's simple enough to include the incoming NTRIP data in the datalog file. I'll put it on the backlog.

Note that DGPS corrections will only be applied to a connected receiver from a LIVE NTRIP data stream, not from a pre-recorded datalog file.

**Comment by semuadmin** [comment]
@foxittt I've uploaded a branch https://github.com/semuconsulting/PyGPSClient/tree/enhance-datalogging which contains enhancements to support NTRIP datalogging. If you want to install and try this version out and let me know how you get on, that would be very helpful.

**Comment by foxittt** [comment]
Thanks!!!
I`ll try!
