### ISSUE TITLE
Is it possible to configure it as a caster using pygpsclient?

### ISSUE THREAD

**Issue by vijaykoundinya** [semuconsulting/PyGPSClient#27]
Thanks in advance

**Comment by semuadmin** [comment]
Hi @vijaykoundinya 

I'm afraid you haven't filled in any of the information on the feature request template so I'm not entirely clear what functionality you're after, but PyGPSClient v1.3.5 already offers a simple NTRIP server/caster facility which is documented in the README here (_it's currently in Beta but is fully functional_):

https://github.com/semuconsulting/PyGPSClient#socketserver

Basically, if you check the Socket/NTRIP Server option at the bottom of the settings panel and then select a Mode of 'NTRIP Server' and a Port of 2101, PyGPSClient will act as a simple NTRIP server/caster with a single mountpoint.

The NTRIP server/caster facility is predicated on the host being connected to an RTK-compatible GNSS receiver operating in RTK Base Station mode. If you're using the popular u-blox ZED-F9P receiver for this purpose, there is a script in the [/examples](https://github.com/semuconsulting/PyGPSClient/tree/master/examples) folder - [f9p-basestation.py](https://github.com/semuconsulting/PyGPSClient/blob/master/examples/f9p_basestation.py) - which illustrates how to configure the ZED-F9P appropriately.

Hope this helps
