### ISSUE TITLE
Exporting parsed UBX data

### ISSUE THREAD

**Issue by fener1efes2** [semuconsulting/PyGPSClient#33]
I have created a .ubx data by using u-center.
PyGPSClient succesfully parsed the data.
But I want to export the data to a txt so that I can depict a graph of certain parameters.
I tried to copy from the console but it did not work. Apart form CTRL + C, CTRL + F does not work in the console.
Since it is not useful to look at the data by using console, there must be a property where users can copy or export the data from the console.

![image](https://user-images.githubusercontent.com/107809055/192163381-65e44d48-92de-4a73-a3bb-e2c0af8c2a8f.png)

**Comment by fener1efes2** [comment]
Data Logging exports the parsed data

**Comment by semuadmin** [comment]
Hi @fener1efes2

Yes, that's the solution I recommend. You can also log the hexadecimal alongside the parsed data for a side-by-side comparison.

FYI if you want a non-GUI way of doing the same thing, the `gnssdump` CLI utilility installed with the `pygnssutils` library also offers configurable extract and logging formats. Type `gnssdump -h` for a full set of parameters.

https://github.com/semuconsulting/pygnssutils#gnssdump
