### ISSUE TITLE
Saving L-band config into D9S

### ISSUE THREAD

**Issue by n8ur** [semuconsulting/PyGPSClient#48]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be a way to save L band configuration info loaded into the NEO-D9S via the SPRTN configuration window.

I was able to set the D9S parameters, but couldn't figure out how to save them to BBRAM/Flash.

**Describe the solution you'd like**

An option to save the D9S configuration in the SPRTN window.

**Describe alternatives you've considered**

I think the only way you could currently save the D9S config is to disconnect from it in the SPRTN window, then reconnect on the main window, go to the UBX config window, and do save config there.  That seems a bit risky, though, as you can't be sure nothing has changed in the connect/reconnect process.

**Would you be willing to contribute a test device?**

I only have one D9S at the moment, but I'm happy to test the code.

**Comment by semuadmin** [comment]
It would be easy enough to add a checkbox on the L-Band panel to execute a CFG-CFG save command to BBR / Flash. Would that address the issue?

**Comment by n8ur** [comment]
That absolutely would.  Thanks!

**Comment by semuadmin** [comment]
> That absolutely would. Thanks!

Done. PR #49 refers.

**Comment by n8ur** [comment]
Thanks!
