### ISSUE TITLE
UI text unreadable in MacOS with Dark theme

### ISSUE THREAD

**Issue by RomanTheLegend** [semuconsulting/PyGPSClient#60]
pygpsclient 1.3.20
MacOs Ventura 13.2.1 (22D68)

When Dark theme in MacOS is enabled, the text in inputboxes and lists is unreadable (same FG and BG color)

![](https://i.ibb.co/DgLvqNY/Screenshot-2023-04-03-at-11-17-40.png)

This is not the issue with Light theme:
![](https://i.ibb.co/dcPCBgt/Screenshot-2023-04-03-at-11-23-09.png)

**Comment by semuadmin** [comment]
Hi @RomanTheLegend 

Unfortunately reliable automatic 'dark mode' detection across different O/S platforms is problematic (though not impossible) with tkinter. There are libraries available e.g. [darkdetect](https://pypi.org/project/darkdetect/), but AFAICS they're not yet fully mature.

The easiest way to address this (from an application standpoint) would be to add a user-selectable colormode option to the application itself, via the new json config file facility introduced in v1.3.22, e.g:

{
...
"colormode": "dark"
...
}

The font colours would then be amended accordingly.

Would that be an acceptable solution?


_As an interim workaround, you could amend the following values in globals.py_:

```
BGCOL = "gray24"  # default widget background color
FGCOL = "white"  # default widget foreground color
```

(_As it happens I normally run in 'Dark' mode on Windows and Linux but reverted to 'Light' on my Mac as too many off-the-shelf applications didn't seem to play well with 'Dark' mode._)

**Comment by RomanTheLegend** [comment]
Yep, that's what I was looking for, thanks

**Comment by semuadmin** [comment]
> Yep, that's what I was looking for, thanks

OK I'll add this to v1.3.23 - may be a couple of weeks.
